site_name: MISA-AKMC Users Manual
repo_url: https://github.com/misa-kmc/
repo_name: misa-kmc/misa-akmc
edit_uri: https://git.hpcer.dev/HPCer/misa-akmc/users-manual/-/edit/master/docs/
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.tabs
  palette:
    scheme: preference
    primary: red
    accent: red

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - 首页: 
    - 概览: index.md
    - 快速开始: quick-start.md
    # - publications.md
  - 编译构建:
    - 准备环境: build/prepare-environment.md
    - 获取源码: build/get-source-code.md
    - 编译: build/build.md
  - 运行:
    - 运行: run/run.md
  - Reference:
    - 配置项说明: reference/reference.md
