site_name: MISA-AKMC Users Manual
repo_url: https://github.com/misa-kmc/
repo_name: misa-kmc/misa-akmc
edit_uri: https://git.hpcer.dev/HPCer/misa-akmc/users-manual/-/edit/master/docs/
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.tabs
  palette:
    scheme: preference
    primary: red
    accent: red

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: true

nav:
  - 首页: 
    - overview.md
    - publications.md
  - 编译构建:
    - 编译: build/build.md
  - 运行:
    - 运行: run/run.md
  - Reference:
    - 配置项说明: reference/reference.md
